### ISSUE TITLE
Making `make start` work with existing database

### ISSUE THREAD

**Issue by Torxed** [riotkit-org/docker-taiga#24]
docker-compose.yaml
```yaml
version: '2'

volumes:
    media:

services:
    taiga:
        image: quay.io/riotkit/taiga:${VERSION}
        environment:
            POSTGRES_DB: ${TAIGA_DB_NAME}
            POSTGRES_PASSWORD: ${TAIGA_DB_PASSWORD}
            POSTGRES_USER: ${TAIGA_DB_USER}
        extra_hosts:
            - "database:172.19.0.1"
        ports:
            - 127.0.0.1:80:80
        volumes:
            # all data placed in volumes are kept between container updates/deletion/recreation
            - media:/usr/src/taiga-back/media
        env_file:
            - .env
```

Only change really in `.env` would be:

```bash
TAIGA_DB_HOST=database
```
