### ISSUE TITLE
Docker-compose.yml traefik, taiga displays strange landing page.

### ISSUE THREAD

**Issue by ghost** [riotkit-org/docker-taiga#32]
Hello all,

I am using the following docker-compose.yml file to start Taiga with Traefik.
```
version: "3"

services:
  taiga:
    image: quay.io/riotkit/taiga:5.0.6
    depends_on:
      - postgres
    volumes:
      - taigamedia:/usr/src/taiga-back/media
    networks:
      - backend
    restart: always
    environment:
      TAIGA_SECRET_KEY: password_key
      TAIGA_HOSTNAME: somehost.com
      TAIGA_SCHEME: https
      TAIGA_DB_NAME: taiga
      TAIGA_DB_USER: taiga
      TAIGA_DB_HOST: postgres
      TAIGA_DB_PASSWORD: password
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:somehost.com; PathPrefixStrip:/taiga
      - traefik.backend=taiga
      - traefik.docker.network=frontend
      - traefik.port=80
      - traefik.frontend.headers.referrerPolicy=no-referrer
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.contentTypeNosniff=true

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: taiga
      POSTGRES_PASSWORD: password
      POSTGRES_USER: taiga
    volumes:
      - postgrestaiga:/var/lib/postgresql/data
    networks:
      - backend
    labels:
      - traefik.enable=false

volumes:
  taigamedia:
  postgrestaiga:

networks:
  backend:
    external: true
```

The compose file executes successfully, however, when heading to hostname.com/taiga the following is displayed.
![taiga](https://user-images.githubusercontent.com/25749668/74386469-eef76500-4ded-11ea-80ba-a85e34eaddff.png)

Am I missing something obvious here?

Thanks.
