### ISSUE TITLE
Question: If I build the container using the following compose file there seems to be no official Taiga documentation for adding my own `contribPlugins` to taiga-frontend.

### ISSUE THREAD

**Issue by Leopere** [riotkit-org/docker-taiga#7]
```YAML
version: '3.7'

services:
  taiga:
#    image: quay.io/riotkit/taiga:4.2.7
    build:
      context: ./docker-taiga/
      #dockerfile: .
      args:
        - TAIGA_BACK_VERSION=4.2.13
        - TAIGA_FRONT_VERSION=4.2.13-stable
    networks:
      - traefik
      - default
    volumes:
      - ./media:/usr/src/taiga-back/media
    environment:
      TAIGA_SECRET_KEY: secret
      TAIGA_HOSTNAME: taiga.REDACTED
      TAIGA_SCHEME: https
      TAIGA_DB_NAME: taiga
      TAIGA_DB_USER: taiga
      TAIGA_DB_HOST: postgres
      TAIGA_DB_PASSWORD: dbpassword
      TAIGA_ENABLE_EMAIL: 'True'
      TAIGA_EMAIL_FROM: REDACTED
      TAIGA_EMAIL_USE_TLS: 'True'
      TAIGA_EMAIL_HOST: REDACTED
      TAIGA_EMAIL_PORT: 465
      TAIGA_EMAIL_USER: REDACTED
      TAIGA_EMAIL_PASS: REDACTED
    #deploy:
    labels:
      - "traefik.backend=taiga"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:taiga.REDACTED"
      - "traefik.enable=true"
      - "traefik.port=80"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
volumes:
  postgres:
  media:
    
networks:
  traefik:
    external: true
```

Any ideas as to how to get contribPlugins working?
